# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: ./example-app


jobs:
   
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
          
    - name: Install dependencies
      run: |
        poetry install --no-root

  linting:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Linting
      run: |
        poetry run task lint
        
  security:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Security testing
      run: |
        poetry run task security
        
  formatter:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Formating
      run: |
        poetry run task formatter
      
  unittest:
    runs-on: ubuntu-latest
    needs: [linting, security, formatter]
    steps:
    - name: Unit tests
      run: |
        poetry run task test

